baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'andre de moraes - template'
author = 'André de Moraes <amancioandre@gmail.com>'

[markup]
[markup.tableOfContents]
endLevel = 2
ordered = true
startLevel = 2